QuickCart.Web/Areas/Admin/Controllers/SubCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using QuickCart.Domain.DTO;
using QuickCart.Services;

namespace QuickCart.Web.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class SubCategoryController : Controller
    {
        private readonly ISubCategoryService _service;
        public SubCategoryController(ISubCategoryService service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
       
            return View();
        }
        public IActionResult Create()
        {

            return View("SubCategoryForm");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SubCategoryFormDTO subCategoryDTO)
        {

            if (ModelState.IsValid)
            {
                var result = _service.Create(subCategoryDTO);
                if (result.Success)
                {
                    TempData["createMesage"] = "Item created successfully!";
                    return RedirectToAction(nameof(Index));
                }
                TempData["deleteMesage"] = result.Message;
                return View("SubCategoryForm", subCategoryDTO);
            }

            return View(subCategoryDTO);
        }


        public IActionResult Edit(int id)
        {

            var result = _service.FirstOrDefault(id);
            if (result.Success)
            {
                return View("SubCategoryForm", result.Data);
            }

            TempData["deleteMesage"] = result.Message;
            return View("SubCategoryForm");

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SubCategoryFormDTO categoryDTO)
        {
            if (ModelState.IsValid)
            {


                var result = _service.Update(categoryDTO);

                if (result.Success)
                {
                    TempData["editMesage"] = "Item edited successfully!";
                    return RedirectToAction(nameof(Index));

                }


            }
            return View("SubCategoryForm", categoryDTO);

        }


        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();

            }

            var result = _service.FirstOrDefault(id);

            return View(result.Data);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCategory(int id)
        {

            var category = _service.FirstOrDefault(id);

            if (category == null)
            {
                return NotFound();
            }
            _service.Delete(id);
            TempData["deleteMesage"] = "Item deleted.";
            return RedirectToAction(nameof(Index));



        }

      
    }
}

QuickCart.Web/Areas/Admin/Views/SubCategory/Delete.cshtml
@model SubCategoryDTO;

@{
    ViewBag.PageTitle = "SubCategory Mangment";
    ViewBag.CardTitle = "Delete ";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<div class="roe">

    <div class="col-md-4">
        <form asp-action="DeleteCategory" method="post">

            <input hidden asp-for="Id" />
            <div class="mb-3">

                <label asp-for="Name"></label>
                <input asp-for="Name" disabled class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="mb-3">

                <label asp-for="Description"></label>
                <input asp-for="Description" disabled class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3 form-group">
                <input type="submit" class="btn btn-danger" value="Delete" />

                <a asp-action="Index" asp-controller="SubCategory" class="btn btn-warning">Back to list</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

QuickCart.Web/Areas/Admin/Views/SubCategory/Index.cshtml
@{
    ViewBag.PageTitle = "Sub Category Mangment";
    ViewBag.CardTitle = "Sub Categories ";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}


<div class="mb-3">
    <a asp-action="Create" asp-controller="SubCategory" class="btn btn-primary">New Sub Category</a>
</div>

<table id="subCategoryDataTable" class="display" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>CreatedAt</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@section Scripts {
    <script src="~/scripts/area/admin/subcategory/subcategorylist.js"></script>

}

QuickCart.Web/Areas/Admin/Views/SubCategory/SubCategoryForm.cshtml
@model SubCategoryFormDTO;

@{
    ViewBag.PageTitle = "SubCategory Mangment";
    ViewBag.CardTitle = (Model == null || Model.Id == 0) ? "Create" : "Edit";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="@ViewBag.CardTitle"  method="post">

            <input hidden asp-for="Id" />
            <div class="mb-3">

                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="mb-3">

                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>


            <div class="mb-3 form-group">
                @if (Model != null)
                {
                    <input type="hidden" id="selectedCategoryId" value="@Model.CategoryId">
                }


                <label asp-for="CategoryId" class="col-form-label"></label>
                <select id="categoryList" asp-for="CategoryId" class="form-control" asp-items="@(new SelectList(string.Empty,"Id","Name"))">
                </select>
                <span class="text-danger" asp-validation-for="CategoryId"></span>

            </div>
            <div class="mb-3 form-group">
                <input type="submit" class="btn btn-primary" value="@((Model == null || Model.Id == 0) ? "Create" : "Edit")" />

                <a asp-action="Index" asp-controller="SubCategory" class="btn btn-warning">Back to list</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/scripts/area/admin/subcategory/subcategoryform.js"></script>
}